FROM ubuntu:16.04
RUN apt-get update --fix-missing && apt-get -y install build-essential curl wget git vim nano cron screen rsyslog iputils-ping
RUN useradd scott
ENTRYPOINT service rsyslog start && service cron start && bash
