version: '2.1'
services:
  ubuntu1604-chromium:
    extends:
      file: ./base.yml
      service: base
    build:
      context: .
      dockerfile: Dockerfile-chromium
    volumes:
      - ./:/mnt/host
      - ~/.Xauthority:/root/.Xauthority
    tty: true
    ports:
      - "${HPORT:-9229}:9229"
    environment:
      - MYNAME=scott
      - DISPLAY=$DISPLAY
    network_mode: "host"
    entrypoint: /usr/bin/chromium-browser --no-sandbox --incognito
