version: '2.1'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - '8080:8080'
      - '50000:50000'
volumes:
  jenkins_home: # use volume, remenber to inspect volume path and backup
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: "${PWD:-/tmp}/jenkins_home" # $PWD is system variable of shell of linux
