version: '2.1'
services:
  ubuntu1604-smokeping:
    extends:
      file: ./base.yml
      service: base
    build:
      context: .
      dockerfile: Dockerfile-smokeping
    volumes:
      - ./:/mnt/host
    tty: true
    ports:
      - "${HPORT:-80}:${CPORT:-80}"
