version: '2.1'
services:
  ubuntu1604-nodebrew:
    extends:
      file: ./base.yml
      service: base
    build:
      context: .
      dockerfile: Dockerfile-nodebrew
    volumes:
      - ./:/mnt/host
    tty: true
    ports:
      - "${HPORT:-3000}:${CPORT:-3000}"
