FROM ubuntu:16.04
RUN apt-get update --fix-missing && apt-get -y install build-essential curl wget git vim nano python python-dev python-pip iputils-ping virtualenv
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN apt-get update
RUN echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update
RUN apt-get -y install google-chrome-stable
RUN apt-get -y install xvfb
ENV PATH /usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV DISPLAY=:9
RUN useradd scott
