FROM ubuntu:16.04
RUN apt-get update --fix-missing && apt-get -y install build-essential curl wget git vim nano python iputils-ping
RUN curl -L git.io/nodebrew | perl - setup
RUN echo "export PATH=\$HOME/.nodebrew/current/bin:\$PATH" >> ~/.bashrc
RUN useradd scott
