FROM ubuntu:16.04
RUN apt-get update --fix-missing && apt-get -y install build-essential curl wget git vim nano cron screen rsyslog iputils-ping libssl-dev openssl
RUN echo deb http://nginx.org/packages/ubuntu/ xenial nginx >> /etc/apt/sources.list && \
	echo deb-src http://nginx.org/packages/ubuntu/ xenial nginx >> /etc/apt/sources.list && \
	apt-get update && apt-get -y --allow-unauthenticated install nginx
RUN useradd scott
