version: '2.1'
services:
  ubuntu1604-base-dev-env:
    extends:
      file: ./base.yml
      service: base
    image: scott1028/base-dev-env:latest
    entrypoint: /bin/bash
    volumes:
      - ./:/mnt/host
    tty: true
