version: '2.1'
services:
  ubuntu1404-pptpd:
    extends:
      file: ./base.yml
      service: base
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile-pptpd
    volumes:
      - ./:/mnt/host
    tty: true
    ports:
      - "1723:1723"
