version: '2.1'
services:
  elasticsearch:
    image: 'library/elasticsearch:6.6.1'
    container_name: elasticsearch
    restart: always
    volumes:
      - elasticsearch_home:/usr/share/elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
      - '5000:5000'
    entrypoint: |
      /bin/sh -c "
      yum install -y centos-release-scl
      yum install -y rh-python36
      yum install -y git
      export PATH="/opt/rh/rh-python36/root/usr/bin:$PATH"
      rm -rf elasticsearch-HQ
      git clone https://github.com/ElasticHQ/elasticsearch-HQ.git
      chmod o+rwx -R /usr/share/elasticsearch
      cd elasticsearch-HQ && pip install -r requirements.txt
      python application.py &
      /usr/local/bin/docker-entrypoint.sh
      "
volumes:
  elasticsearch_home: # use volume, remenber to inspect volume path and backup
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: "${PWD:-/tmp}/elasticsearch_home" # $PWD is system variable of shell of linux
